// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyfxhvhdvzjqmyrhviuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZnhodmhkdnpqcW15cmh2aXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODQwMjAsImV4cCI6MjA1Nzg2MDAyMH0.-QiCnjqEHe4gyOpBop_CiZk_i5bueFpR4AnvIKX2xME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);